### ISSUE TITLE
Fix _verify_payload() of mock_pushover_server

### ISSUE THREAD

**Issue by cthoyt** [scolby33/event_notifier#5]
It appears to work sometimes, which is probably worse than not working at all. Also perhaps an improved implementation of the rest of mock_pushover_server

**Comment by scolby33** [comment]
Partially fixed. Verification works properly for required parameters, but `type` and `valid_values` are not checked at all for optional parameters.

**Comment by scolby33** [comment]
Apparently you can't assign multiple people.

**Comment by scolby33** [comment]
Closed with 19849d1
